#!/bin/bash

IFS=":"
count=0; noexe=0
for directory in $PATH; do
	if [ -d $directory ]; then
		for cmd in "$directory"/*; do
			if [ -x "$cmd" ]; then
				count=$(($count + 1))
			else
				noexe=$(($noexe + 1))
			fi
		done
	fi
done

echo "$count commands, and $noexe entries that weren't executable"
exit 0
