#!/bin/bash

getopts c:d: op

case $op 
in
	d) k=$OPTARG
	ans=$(expr $k \* 10000)
	echo "The $k km is converter to $ans decimeter";;
	c) k=$OPTARG
	ans=$(expr $k \* 100000)
	echo "The $k is converter to $ans centimeter";;
	?) k=$1
	ans=$(expr $k \* 1000)
	echo "The $1 is converter to $ans meter";;
esac
